"""
Benchmark conversations for the evaluation scripts.

A  the conversation the extractor was originally tuned on (26 turns, 10 facts)
B  a held-out conversation with different phrasings (24 turns, 10 facts)
C  a scale/generalisation stress set: ~150 turns, 40 facts, and filler that
   looks factual — capitalised names, numbers, dates that answer no question.

Each QUESTIONS_* entry is (question, [keywords]); a fact counts as captured
when one of its keywords appears in the pack.
"""

CONV_A = [('user',
"Morning! Quick intro since we haven't talked before: people call me Marta."),
('assistant', 'Nice to meet you, Marta. What shall we look at today?'),
('user', "First, some background. I'm based in Utrecht, near the old canal."),
('assistant', 'Utrecht is lovely. Go on.'),
('user', 'I work as a nurse, mostly night shifts, so I reply at odd hours.'),
('assistant', 'Good to know, no rush on replies then.'),
('user',
'The traffic was horrible this morning, took me an hour to get home.'),
('assistant', 'An hour! That sounds exhausting after a night shift.'),
('user', 'Lately I code in Rust for fun, little command line things.'),
('assistant', 'Rust is a great choice for CLI tools.'),
('user', 'Oh before I forget: the sprint demo is on Friday at 10:00.'),
('assistant', 'Noted, sprint demo Friday at 10:00.'),
('user', 'Our project is codenamed heron-nest, silly name but it stuck.'),
('assistant', 'heron-nest, got it. Who picked that?'),
('user',
'Long story. Anyway, my dog is called Bikkel and he ate my charger cable.'),
('assistant', 'Bikkel sounds like a handful!'),
('user', 'He is. By the way, please keep explanations brief, I skim a lot.'),
('assistant', 'Will do, brief it is.'),
('user',
'Did you see the football match yesterday? What a mess in the second half.'),
('assistant', 'I heard it was quite the upset.'),
('user', 'Also important: the report is due March 3rd, hard deadline.'),
('assistant', 'March 3rd, noted as a hard deadline.'),
('user',
'We track tasks in Trello, in case you need to reference the board.'),
('assistant', 'Understood, Trello board it is.'),
('user',
'I should get some sleep soon. The rain is tapping on the window, cozy.'),
('assistant', 'Sleep well, Marta. We can pick this up later.')]

QUESTIONS_A = [("What is the user's name?", ['marta']),
('Where does the user live?', ['utrecht']),
("What is the user's job?", ['nurse']),
('Which programming language does the user use?', ['rust']),
('When is the sprint demo?', ['friday']),
('What is the project codenamed?', ['heron-nest', 'heron']),
("What is the dog's name?", ['bikkel']),
('How should explanations be written?', ['brief', 'short']),
('When is the report due?', ['march']),
('Where are tasks tracked?', ['trello'])]

CONV_B = [('user', 'Hey there, new here. Everyone calls me Joris, by the way.'),
('assistant', 'Welcome, Joris! What brings you in?'),
('user', "I'm living over in Groningen these days, moved last spring."),
('assistant', 'Groningen, nice. How are you finding it?'),
('user', 'Busy! My day job is teaching math at a secondary school.'),
('assistant', 'A math teacher, great. What can I help with?'),
('user', "So, most of my scripts are in TypeScript, for what it's worth."),
('assistant', 'TypeScript noted.'),
('user', 'Ugh, my coffee machine broke again this morning. Third time.'),
('assistant', "Third time! Maybe it's beyond saving."),
('user', 'Heads up: the kickoff call lands on Wednesday at 09:30.'),
('assistant', 'Kickoff Wednesday at 09:30, got it.'),
('user', "We named the repo willow-basket, don't ask why."),
('assistant', 'willow-basket it is.'),
('user', 'My cat Muis knocked a plant off the shelf while I typed this.'),
('assistant', 'Muis sounds mischievous.'),
('user',
'One thing: answer me with bullet points please, walls of text lose me.'),
('assistant', 'Bullet points from here on.'),
('user', 'The weather forecast says storm tomorrow, so I might be offline.'),
('assistant', 'Stay safe if the storm hits.'),
('user', "Don't let me forget, the invoice must be paid by June 12th."),
('assistant', 'Invoice by June 12th, noted.'),
('user', 'Issues live in GitHub, not email. People keep emailing me anyway.'),
('assistant', 'GitHub for issues, understood.')]

QUESTIONS_B = [("What is the user's name?", ['joris']),
('Where does the user live?', ['groningen']),
("What is the user's job?", ['teach', 'math']),
('Which programming language does the user use?', ['typescript']),
('When is the kickoff call?', ['wednesday']),
('What is the repo named?', ['willow-basket', 'willow']),
("What is the cat's name?", ['muis']),
('How should answers be formatted?', ['bullet']),
('When must the invoice be paid?', ['june']),
('Where do issues live?', ['github'])]

CONV_C = [('user', 'Hi! Long one today, I have a pile of things to dump on you.'),
('assistant', "Go ahead, I'll keep up."),
('user', 'You can address me as Wietse, everyone does.'),
('assistant', 'Nice to meet you, Wietse.'),
('user',
'The tram was packed this morning, some guy played trumpet the whole way.'),
('assistant', 'A trumpet on a packed tram sounds like a lot.'),
('user',
"I'm situated in Antwerp now, moved down from Rotterdam two years back."),
('assistant', "Antwerp is a good city. How's the move settled?"),
('user',
'Settled fine. My role is lead data engineer, if that matters for context.'),
('assistant', 'Noted, data engineering lead.'),
('user',
'I saw a documentary about Voyager 2 last night, hard to sleep after.'),
('assistant', 'Voyager documentaries do that.'),
('user', "I'm employed at Kestrel Analytics, been there since 2023."),
('assistant', 'Kestrel Analytics, understood.'),
('user',
'Most of what I build is in Go these days, some Python glue around it.'),
('assistant', 'Go with Python glue, got it.'),
('user', 'My editor is Neovim and I will not be taking questions on that.'),
('assistant', 'Neovim it is, no questions asked.'),
('user',
'Rain again. It has rained eleven days straight, which must be a record.'),
('assistant', 'Eleven days is grim.'),
('user',
'We store everything in Postgres, with Redis in front for the hot keys.'),
('assistant', 'Postgres primary, Redis cache. Noted.'),
('user', 'Deploys go out on Fly.io, we moved off Heroku in the spring.'),
('assistant', 'Fly.io for deploys.'),
('user', 'CI runs on GitHub Actions, roughly nine minutes end to end.'),
('assistant', 'GitHub Actions, nine minute pipeline.'),
('user',
'My machine only has 8GB of VRAM, so big models are out of reach locally.'),
('assistant', '8GB VRAM is a real constraint, yes.'),
('user', 'I run Gemma on llama.cpp for the local experiments.'),
('assistant', 'Gemma via llama.cpp, understood.'),
('user',
'Someone left a whole tray of speculoos in the kitchen and it vanished in an '
'hour.'),
('assistant', 'Speculoos does not survive long.'),
('user', 'Standup happens at 09:15 every weekday, keep that slot clear.'),
('assistant', 'Standup 09:15 daily, noted.'),
('user',
'There are seven of us on the team, four engineers and three analysts.'),
('assistant', 'A team of seven.'),
('user', "My manager is Priya, she's the one who signs off on scope."),
('assistant', 'Priya signs off on scope. Got it.'),
('user', 'Honestly the office coffee is undrinkable. I bring my own now.'),
('assistant', 'Bringing your own is usually the winning move.'),
('user', "The repo is called amber-lattice, and no, I didn't pick the name."),
('assistant', 'amber-lattice. Noted, and no judgement.'),
('user', 'Beta ships October 14th, that date is not moving.'),
('assistant', 'October 14th for beta, hard date.'),
('user', "Our client on this one is Vandermeer BV, they're quite formal."),
('assistant', 'Vandermeer BV, formal tone. Understood.'),
('user', 'The budget for the whole thing is 12000 euro, which is not much.'),
('assistant', '12000 euro budget noted.'),
('user', 'I read The Dispossessed again over the holidays, still holds up.'),
('assistant', 'Le Guin does hold up.'),
('user',
'Please answer me in bullet points, walls of text lose me completely.'),
('assistant', 'Bullet points from here on.'),
('user', 'And skip the emoji, I find them noisy.'),
('assistant', 'No emoji. Noted.'),
('user', 'Use metric units, always. Fahrenheit means nothing to me.'),
('assistant', 'Metric only.'),
('user', 'My daughter Lotte is six and she has opinions about dinosaurs.'),
('assistant', 'Six-year-olds usually do.'),
('user',
'We also have a rabbit named Stroopwafel, my partner picked the name.'),
('assistant', 'Stroopwafel the rabbit. Excellent.'),
('user',
"I'm allergic to shellfish, quite badly, so restaurants need checking."),
('assistant', "Shellfish allergy noted, that's important."),
('user',
'Also vegetarian since university, which makes the shellfish thing '
'academic.'),
('assistant', 'Vegetarian too, understood.'),
('user',
"My brother Sander is visiting in two weeks, so I'll be scarce then."),
('assistant', "Sander visiting, you'll be scarce."),
('user', 'Did you see the match? Absolute disaster in the second half.'),
('assistant', 'I heard it went badly.'),
('user', "I'm in the CET timezone, in case you're scheduling anything."),
('assistant', 'CET noted for scheduling.'),
('user', 'I train Tuesdays and Thursdays, so evenings those days are gone.'),
('assistant', 'Tuesday and Thursday evenings blocked.'),
('user',
'I play bass in a band called Lage Landen, we gig maybe twice a month.'),
('assistant', 'Bass in Lage Landen, twice a month.'),
('user',
'The neighbours are renovating. Drilling started at 7am, on a Saturday.'),
('assistant', '7am drilling on a Saturday is a crime.'),
('user',
"I'm flying to Lisbon on the 9th for a conference, back on the 13th."),
('assistant', 'Lisbon the 9th to the 13th.'),
('user', 'Staying at the Hotel Estrela, walking distance from the venue.'),
('assistant', 'Hotel Estrela, noted.'),
('user',
'My goal this year is to finish the thesis by spring, everything else is '
'secondary.'),
('assistant', 'Thesis by spring is the priority.'),
('user',
'The thesis is on distributed consensus, specifically Raft variants.'),
('assistant', 'Distributed consensus, Raft variants.'),
('user',
'My supervisor is Professor Aaltink, he replies to email roughly never.'),
('assistant', 'Professor Aaltink, slow to reply.'),
('user', 'I drive a Skoda Octavia, ancient but it starts every time.'),
('assistant', 'The Octavia is a reliable thing.'),
('user', 'Parking near the office costs 4 euro an hour, which adds up fast.'),
('assistant', 'Expensive parking, yes.'),
('user', 'We use Linear for issue tracking, not Jira, thank goodness.'),
('assistant', 'Linear for issues.'),
('user', 'Design files live in Figma, ask me if you need a link.'),
('assistant', 'Figma for design.'),
('user', 'Docs are in Notion, though half of them are out of date.'),
('assistant', 'Notion for docs.'),
('user', "I hate video calls before 10, my brain isn't online yet."),
('assistant', 'No calls before 10.'),
('user',
'Weirdly, the best croissant in the city is from a petrol station on the '
'ring road.'),
('assistant', 'Petrol station croissants are an underrated genre.'),
('user', "My phone is an old Pixel, I'm refusing to upgrade until it dies."),
('assistant', 'Riding the Pixel until the end.'),
('user', 'I speak Dutch and English, and enough German to order food badly.'),
('assistant', 'Dutch, English, some German.'),
('user',
"Prefer that you write to me in English, though, it's what I work in."),
('assistant', 'English it is.'),
('user',
'The staging environment is at staging.kestrel.internal, behind the VPN.'),
('assistant', 'Staging behind the VPN, noted.'),
('user', "Our on-call rotation is weekly and I'm on next starting Monday."),
('assistant', 'On-call from Monday, understood.'),
('user', 'Incidents get logged in PagerDuty, that part actually works well.'),
('assistant', 'PagerDuty for incidents.'),
('user', 'My birthday is on the 22nd of November, not that you need it.'),
('assistant', '22 November noted.'),
('user', 'I once broke production on my second day. Nobody has let it go.'),
('assistant', 'That story does tend to stick.'),
('user', 'The retro is every second Friday at 16:00, usually runs long.'),
('assistant', 'Retro biweekly Friday 16:00.'),
('user',
'Invoices must be submitted before the 25th or finance gets grumpy.'),
('assistant', 'Invoices before the 25th.'),
('user',
'Our biggest competitor is Nachtvogel, they undercut us constantly.'),
('assistant', 'Nachtvogel, the undercutter.'),
('user', "I'm learning Portuguese slowly, mostly for the Lisbon trips."),
('assistant', 'Portuguese in progress.'),
('user', "That's most of it, I think. My head is empty now."),
('assistant', 'Plenty captured. Ask me anything from it later.')]

QUESTIONS_C = [("What is the user's name?", ['wietse']),
('Where does the user live?', ['antwerp']),
("What is the user's job or role?", ['data engineer', 'data']),
('Who does the user work for?', ['kestrel']),
('Which programming language does the user use?', ['go']),
('Which editor does the user use?', ['neovim']),
('Which database do they use?', ['postgres']),
('Where do they deploy?', ['fly.io', 'fly']),
('What runs their CI?', ['github actions', 'github']),
("How much VRAM does the user's machine have?", ['8gb', '8 gb']),
('Which model does the user run locally?', ['gemma']),
('When is standup?', ['09:15', '9:15']),
('How many people are on the team?', ['seven']),
("Who is the user's manager?", ['priya']),
('What is the repo called?', ['amber-lattice', 'amber']),
('When does the beta ship?', ['october']),
('Who is the client?', ['vandermeer']),
('What is the budget?', ['12000']),
('How should answers be formatted?', ['bullet']),
('Should the assistant use emoji?', ['emoji']),
('Which units should be used?', ['metric']),
("What is the user's daughter called?", ['lotte']),
("What is the rabbit's name?", ['stroopwafel']),
('What is the user allergic to?', ['shellfish']),
("What are the user's dietary requirements?", ['vegetarian']),
("What is the user's brother called?", ['sander']),
('Which timezone is the user in?', ['cet']),
('Which days does the user train?', ['tuesday']),
('What band does the user play in?', ['lage landen', 'lage']),
('When is the user flying to Lisbon?', ['9th', 'lisbon']),
('Which hotel is the user staying at?', ['estrela']),
("What is the user's goal this year?", ['thesis']),
('What is the thesis about?', ['consensus', 'raft']),
("Who is the user's supervisor?", ['aaltink']),
('Where are issues tracked?', ['linear']),
('Where do design files live?', ['figma']),
('Where are the docs?', ['notion']),
('When is the retro?', ['friday', '16:00']),
('When are invoices due?', ['25th']),
('Who is the biggest competitor?', ['nachtvogel'])]

DISTRACTOR_STRINGS = ['voyager',
'speculoos',
'croissant',
'trumpet',
'eleven days',
'the dispossessed',
'second half',
'drilling',
'parking',
'pixel']

